from dotenv import load_dotenv
import os

load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")

DATABASE_NAME = os.getenv("DATABASE_NAME")

KAFKA_BOOTSTRAP_SERVERS = os.getenv(
    "KAFKA_BOOTSTRAP_SERVERS"
)

QR_SCAN_TOPIC = os.getenv(
    "QR_SCAN_TOPIC"
)

VALIDATION_RESULTS_TOPIC = os.getenv(
    "VALIDATION_RESULTS_TOPIC"
)

RETRY_VALIDATION_TOPIC = os.getenv(
    "RETRY_VALIDATION_TOPIC"
)

DEAD_LETTER_TOPIC = os.getenv(
    "DEAD_LETTER_TOPIC"
)

MAX_RETRY_ATTEMPTS = 3

INITIAL_RETRY_DELAY = 5